### ISSUE TITLE
Missing few files.

### ISSUE THREAD

**Issue by superhealing** [Mohanbarman/config#1]
Hello, seem is missing a few things here, mostly one is 
`# program launcher
super + space
	exec /home/mohan/MyScripts/menu`
Maybe also nemo config too?
Also about the fonts, tried using fc-cache dirthatcointainfont
after restart seem still polybar don't work.
Thank you to share the amazing dotfiles.

**Comment by Mohanbarman** [comment]
I have removed that menu script in my latest config . Sorry about that `sxhkdrc` was old i have updated it and you can find rofi configs in rofi/ dir . To get the nemo colors you have to install [flat-remix-green](https://www.gnome-look.org/p/1297346/) gtk theme . For fonts move both font archives icomoon.ttf and icomoon.woff to /usr/share/fonts/icomoon directory and then run `sudo fc-cache -f`

**Comment by Mohanbarman** [comment]
If it doesn't worked with icomoon.ttf you can try with icomoon.woff font in fonts/ dir
